/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/internal/tasks/process-notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NotificationWebhookController_processNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_readinessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create presigned upload URLs
         * @description Creates pending media records and returns temporary upload URLs for direct cloud storage upload.
         */
        post: operations["UploadsController_getPresignedUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm uploaded asset
         * @description Marks a pending media asset as confirmed after direct cloud upload succeeds.
         */
        post: operations["UploadsController_confirmUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create employee
         * @description Creates an employee record. Requires an ADMIN session.
         */
        post: operations["EmployeeController_createEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an interior quote
         * @description Stores quote details, calculates an estimate, and dispatches a notification.
         */
        post: operations["QuoteController_requestQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MetricsController_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with employee credentials
         * @description Creates a server-side session and sets the session cookie.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current session user
         * @description Returns the user stored in the current session cookie.
         */
        get: operations["AuthController_getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out current user
         * @description Destroys the active session and clears the session cookie.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate employee account
         * @description Sets the initial password for an employee account and creates a session.
         */
        post: operations["UserController_activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/{employeeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user by employee ID */
        delete: operations["UserController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FileItemDto: {
            /**
             * @description Original filename to upload.
             * @example living-room-render.webp
             */
            fileName: string;
            /**
             * @description Allowed file MIME type.
             * @example image/webp
             * @enum {string}
             */
            mimeType: "image/jpeg" | "image/png" | "image/webp" | "application/pdf";
            /**
             * @description File size in bytes.
             * @example 524288
             */
            fileSize: number;
            /**
             * @description Logical upload category.
             * @example portfolio
             */
            category: string;
        };
        GenerateUrlDto: {
            /** @description Files that need presigned upload URLs. */
            files: components["schemas"]["FileItemDto"][];
            /**
             * @description Storage provider to use for the upload.
             * @example r2
             * @enum {string}
             */
            provider: "r2" | "gcs";
        };
        PresignedUrlResponseDto: {
            /**
             * @description Temporary URL used by the client to upload the file.
             * @example https://storage.example.com/catalog/images/kitchen/file.webp?signature=...
             */
            uploadUrl: string;
            /**
             * @description Public URL where the uploaded asset will be available.
             * @example https://cdn.example.com/catalog/images/kitchen/file.webp
             */
            publicUrl: string;
            /**
             * @description Storage object key for the uploaded file.
             * @example catalog/images/kitchen/681ef9c6-file.webp
             */
            fileKey: string;
        };
        ConfirmUploadDto: {
            /**
             * @description Storage object key returned by the presigned upload flow.
             * @example quotes/client-render.webp
             */
            fileKey: string;
        };
        ConfirmUploadResponseDto: {
            /**
             * @description Storage object key that was confirmed.
             * @example catalog/images/kitchen/681ef9c6-file.webp
             */
            fileKey: string;
            /**
             * @description Public URL for the confirmed asset.
             * @example https://cdn.example.com/catalog/images/kitchen/file.webp
             */
            publicUrl: string;
            /**
             * @description Asset status after confirmation.
             * @example confirmed
             */
            status: string;
        };
        AddressDto: {
            /**
             * @description Type of employee address.
             * @example CURRENT
             * @enum {string}
             */
            type: "PERMANENT" | "CURRENT" | "OFFICE";
            /**
             * @description Street address line.
             * @example 12 MG Road
             */
            street: string;
            /**
             * @description City for the address.
             * @example Bengaluru
             */
            city: string;
            /**
             * @description State for the address.
             * @example Karnataka
             */
            state: string;
            /**
             * @description Postal or ZIP code.
             * @example 560001
             */
            postalCode: string;
            /**
             * @description Country for the address.
             * @example India
             */
            country: string;
        };
        CreateEmployeeDto: {
            /**
             * @description Unique employee identifier.
             * @example SE282
             */
            empId: string;
            /**
             * @description Employee first name.
             * @example Aarav
             */
            firstName: string;
            /**
             * @description Employee last name.
             * @example Sharma
             */
            lastName: string;
            /**
             * @description Employee email address.
             * @example aarav.sharma@example.com
             */
            email: string;
            /**
             * @description Employee role in the organization.
             * @example EMPLOYEE
             * @enum {string}
             */
            role: "MANAGER" | "EMPLOYEE" | "IT" | "HR" | "PMO" | "ADMIN";
            /** @description Employee addresses. */
            addresses: components["schemas"]["AddressDto"][];
        };
        MessageResponseDto: {
            /**
             * @description Human-readable operation result message.
             * @example Operation completed successfully
             */
            message: string;
        };
        RoomCountsDto: {
            /**
             * @description Living rooms count.
             * @example 1
             */
            living: number;
            /**
             * @description Kitchens count.
             * @example 1
             */
            kitchen: number;
            /**
             * @description Bedrooms count.
             * @example 2
             */
            bedroom: number;
            /**
             * @description Bathrooms count.
             * @example 2
             */
            bathroom: number;
            /**
             * @description Dining rooms count.
             * @example 1
             */
            dining?: number;
        };
        CreateQuoteDto: {
            /**
             * @description Home or apartment configuration.
             * @example 2 BHK
             */
            bhkType: string;
            /** @description Room counts used to calculate the estimate. */
            rooms: components["schemas"]["RoomCountsDto"];
            /**
             * @description Selected interior package.
             * @example Premium
             */
            package: string;
            /**
             * @description Client name.
             * @example Priya Nair
             */
            name: string;
            /**
             * @description Indian phone number for quote follow-up.
             * @example +919876543210
             */
            phone: string;
            /**
             * @description Client email address.
             * @example priya.nair@example.com
             */
            email: string;
        };
        CreateQuoteResponseDto: {
            /**
             * @description Whether the quote request was stored successfully.
             * @example true
             */
            success: boolean;
            /**
             * @description Quote creation result message.
             * @example Quote generated successfully
             */
            message: string;
            /**
             * @description Stored quote identifier.
             * @example 681ef9c6f24f8f2a2e2d5c1b
             */
            quoteId: string;
            /**
             * @description Calculated estimate amount.
             * @example 350000
             */
            estimatedPrice: number;
        };
        LoginDto: {
            /**
             * @description Username or employee identifier used to sign in.
             * @example SE282
             */
            username: string;
            /**
             * @description Account password.
             * @example StrongPass123
             */
            password: string;
        };
        AuthUserDto: {
            /**
             * @description Internal user identifier.
             * @example 681ef9c6f24f8f2a2e2d5c1b
             */
            userId: string;
            /**
             * @description Employee identifier linked to the user account.
             * @example SE282
             */
            employeeId: string;
            /**
             * @description Current user role.
             * @example ADMIN
             */
            role: string;
            /**
             * @description Display name for the authenticated user.
             * @example System Admin
             */
            name?: string;
        };
        AuthResponseDto: {
            /**
             * @description Authentication result message.
             * @example Login successful
             */
            message: string;
            /** @description Authenticated user session payload. */
            user: components["schemas"]["AuthUserDto"];
        };
        CurrentUserResponseDto: {
            /** @description Current authenticated user from the session. */
            user: components["schemas"]["AuthUserDto"];
        };
        ActivateUserDto: {
            /**
             * @description Employee identifier for the account being activated.
             * @example SE282
             */
            employeeId: string;
            /**
             * @description Password to set for the employee account.
             * @example StrongPass123
             */
            password: string;
        };
        ActivateUserResponseDto: {
            /**
             * @description Activation result message.
             * @example Account activated successfully. You are now logged in.
             */
            message: string;
            /**
             * @description Created or activated user identifier.
             * @example 681ef9c6f24f8f2a2e2d5c1b
             */
            userId: string;
            /**
             * @description Employee identifier linked to the activated user.
             * @example SE282
             */
            employeeId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    NotificationWebhookController_processNotification: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
                "x-cloudtasks-taskname": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_readinessCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    UploadsController_getPresignedUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateUrlDto"];
            };
        };
        responses: {
            /** @description Presigned URLs were generated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUrlResponseDto"][];
                };
            };
            /** @description Current session user does not have the ADMIN role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UploadsController_confirmUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmUploadDto"];
            };
        };
        responses: {
            /** @description Upload was confirmed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmUploadResponseDto"];
                };
            };
            /** @description Current session user does not have the ADMIN role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeController_createEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeDto"];
            };
        };
        responses: {
            /** @description Employee was created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
            /** @description Current session user does not have the ADMIN role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employee ID or email already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QuoteController_requestQuote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuoteDto"];
            };
        };
        responses: {
            /** @description Quote request was created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateQuoteResponseDto"];
                };
            };
        };
    };
    MetricsController_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login succeeded and session was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Credentials are invalid or the user cannot be authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user session payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponseDto"];
                };
            };
            /** @description Session cookie is missing or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout succeeded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    UserController_activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateUserDto"];
            };
        };
        responses: {
            /** @description Account activated and session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivateUserResponseDto"];
                };
            };
        };
    };
    UserController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Employee identifier for the user account to delete. */
                employeeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User was deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
            /** @description Current session user does not have the ADMIN role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No user was found for the supplied employee ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
