export interface CountryCode {
  code: string;
  iso: string;
  name: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: "+91", iso: "IN", name: "India" },
  { code: "+1", iso: "US", name: "United States" },
  { code: "+44", iso: "GB", name: "United Kingdom" },
  { code: "+971", iso: "AE", name: "United Arab Emirates" },
  { code: "+65", iso: "SG", name: "Singapore" },
  { code: "+61", iso: "AU", name: "Australia" },
  { code: "+1", iso: "CA", name: "Canada" },
  { code: "+966", iso: "SA", name: "Saudi Arabia" },
  { code: "+64", iso: "NZ", name: "New Zealand" },
  { code: "+33", iso: "FR", name: "France" },
  { code: "+49", iso: "DE", name: "Germany" },
  { code: "+353", iso: "IE", name: "Ireland" },
  { code: "+965", iso: "KW", name: "Kuwait" },
  { code: "+974", iso: "QA", name: "Qatar" },
  { code: "+968", iso: "OM", name: "Oman" },
  { code: "+973", iso: "BH", name: "Bahrain" },
  { code: "+60", iso: "MY", name: "Malaysia" },
  { code: "+81", iso: "JP", name: "Japan" },
  { code: "+86", iso: "CN", name: "China" },
  { code: "+82", iso: "KR", name: "South Korea" },
  { code: "+39", iso: "IT", name: "Italy" },
  { code: "+34", iso: "ES", name: "Spain" },
  { code: "+7", iso: "RU", name: "Russia" },
  { code: "+55", iso: "BR", name: "Brazil" },
  { code: "+27", iso: "ZA", name: "South Africa" },
  { code: "+234", iso: "NG", name: "Nigeria" },
  { code: "+254", iso: "KE", name: "Kenya" },
  { code: "+20", iso: "EG", name: "Egypt" },
  { code: "+92", iso: "PK", name: "Pakistan" },
  { code: "+880", iso: "BD", name: "Bangladesh" },
  { code: "+94", iso: "LK", name: "Sri Lanka" },
  { code: "+977", iso: "NP", name: "Nepal" },
  { code: "+62", iso: "ID", name: "Indonesia" },
  { code: "+63", iso: "PH", name: "Philippines" },
  { code: "+66", iso: "TH", name: "Thailand" },
  { code: "+84", iso: "VN", name: "Vietnam" },
  { code: "+41", iso: "CH", name: "Switzerland" },
  { code: "+31", iso: "NL", name: "Netherlands" },
  { code: "+32", iso: "BE", name: "Belgium" },
  { code: "+46", iso: "SE", name: "Sweden" },
  { code: "+47", iso: "NO", name: "Norway" },
  { code: "+45", iso: "DK", name: "Denmark" },
  { code: "+358", iso: "FI", name: "Finland" },
  { code: "+43", iso: "AT", name: "Austria" },
  { code: "+30", iso: "GR", name: "Greece" },
  { code: "+90", iso: "TR", name: "Turkey" },
  { code: "+52", iso: "MX", name: "Mexico" },
  { code: "+54", iso: "AR", name: "Argentina" },
  { code: "+56", iso: "CL", name: "Chile" },
  { code: "+57", iso: "CO", name: "Colombia" },
  { code: "+51", iso: "PE", name: "Peru" },
];
